### PR TITLE
Changed card creation to dynamic

### PR DESCRIPTION
**Pull request by thelaurafranklin**
Currently, it is still creating a set number (6) of pairs.  Next PR will add the levels functionality.  Part of #17

### CODE REVIEW

**Comment by adnanusman** [comment]
Hey @flaura42 will try to get to these as soon as I can :) Thank you!

**Comment by adnanusman** [comment]
I see some weird behavior happening when I hit the reset button, I'll have to investigate this further.

**Comment by thelaurafranklin** [comment]
What kind of weird behavior??

**Comment by adnanusman** [comment]
sorry, I should have given more information. It seems to create more cards than the original.

**Comment by thelaurafranklin** [comment]
New Levels PR will completely replace this one, so I am closing it

**Pull request closed without merging**
